#!/bin/sh

set -eu

AIRCONNECT_DIR="/var/packages/AirConnect/target"

start_airconnect ()
{
    logfile=/tmp/airupnp.log
    touch "${logfile}"
    chown airconnect:users "${logfile}"

    ips=$(ifconfig -a | grep 'Ethernet' -A 1 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')

    if [ -z "$ips" ]; then
        echo "Failed to get the Ethernet interfaces" > "${SYNOPKG_TEMP_LOGFILE}"
        exit 1
    fi

    ip=$(echo "${ips}" | grep -E "^10\\." | head -n 1)
    if [ -z "${ip}" ]; then
        ip=$(echo "${ips}" | grep -E "^192\\.168\\." | head -n 1)
    fi
    if [ -z "${ip}" ]; then
        echo "Failed to get local IP address (10.* or 192.168.*)" > "${SYNOPKG_TEMP_LOGFILE}"
        exit 1
    fi

    port=49154
    echo "[$(date +'%T')] Starting airupnp on ${ip}:${port}" >> ${logfile}

    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp -b ${ip}:${port} -z -l 1000:2000 -f ${logfile} -d all=error" >> ${logfile} 2>&1
}

stop_airconnect ()
{
    killall -15 airupnp
}

airconnect_status ()
{
    # shellcheck disable=SC2009
    if ! ps | grep airupnp | grep -v -q grep
    then
        return 1
    else
        return 0
    fi
}

case $1 in
    start)
        echo Starting AirConnect ...
        start_airconnect
        exit $?
        ;;
    stop)
        echo Stopping AirConnect ...
        stop_airconnect
        exit $?
        ;;
    status)
        if airconnect_status
        then
            echo AirConnect is running
            exit 0
        else
            echo AirConnect is not running
            exit 1
        fi
        ;;
    log)
        echo "/tmp/airupnp.log"
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
