#!/bin/sh

AIRCONNECT_DIR="/var/packages/AirConnect/target"

start_airconnect ()
{
    IP=$(/sbin/ifconfig lbr0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
    PORT=49154
    ${AIRCONNECT_DIR}/airupnp-arm -b ${IP}:${PORT} -z -l 1000:2000 -f /tmp/airupnp-arm.log -d all=error
}

stop_airconnect ()
{
    killall -15 airupnp-arm
}

airconnect_status ()
{
    if [ ! ps | grep airupnp-arm | grep -v -q grep ]
    then
        return 1
    else
        return 0
    fi
}

case $1 in
    start)
        echo Starting AirConnect ...
        start_airconnect
        exit $?
        ;;
    stop)
        echo Stopping AirConnect ...
        stop_airconnect
        exit $?
        ;;
    status)
        if airconnect_status
        then
            echo AirConnect is running
            exit 0
        else
            echo AirConnect is not running
            exit 1
        fi
        ;;
    log)
        echo "/tmp/airupnp-arm.log"
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
